name: CI

on:
  push:
  pull_request:

jobs:
  foundry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source ~/.bashrc || true
          foundryup

      - name: Build
        working-directory: contracts
        run: forge build --sizes

      - name: Test
        working-directory: contracts
        run: forge test -vvv
