name: Validate Claims

on:
  push:
    paths:
      - 'docs/claims/**/*.json'
      - 'scripts/validate_claims.sh'
      - '.github/workflows/validate-claims.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq & Foundry (and expose PATH in this step)
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y jq
          curl -L https://foundry.paradigm.xyz | bash
          # PATH'i BU ADIM için de ekle
          export PATH="$HOME/.foundry/bin:$PATH"
          # Bazı runner'larda tam yol gerekebiliyor
          ~/.foundry/bin/foundryup -v || foundryup -v
          ~/.foundry/bin/cast --version || cast --version
          jq --version
          # Sonraki adımlar için kalıcı
          echo "$HOME/.foundry/bin" >> "$GITHUB_PATH"

      - name: Run validator
        env:
          RPC_URL: ${{ secrets.OG_RPC_URL }}
        run: |
          set -euxo pipefail
          which cast
          cast --version
          bash scripts/validate_claims.sh
