name: validate-claims (cron)

on:
  schedule:
    - cron: "17 2 * * *"   # UTC; her gün 05:17 TR
  push:
    paths:
      - "docs/claims/**/*.json"
      - "scripts/validate_claims.sh"
      - ".github/workflows/validate-claims.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: validate-claims
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y jq
          jq --version

      # Foundry'yi resmi action ile kurar; forge/cast PATH'e eklenir
      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show versions
        shell: bash
        run: |
          set -euo pipefail
          forge --version
          cast --version

      - name: Run validator
        env:
          OG_RPC_URL: ${{ secrets.OG_RPC_URL }}   # yoksa public RPC kullanacağız
        shell: bash
        run: |
          set -euo pipefail
          # RPC fallback: secret yoksa public 0G Galileo RPC
          RPC_URL="${OG_RPC_URL:-https://evmrpc-testnet.0g.ai}"
          export RPC_URL
          export CHAIN_ID=16601
          bash scripts/validate_claims.sh
